FROM rust:slim

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y \
    libasound2 \
    libopus0 \
    libssl3 \
    zlib1g \
    python3 \
    curl \
    libssl-dev \
    pkg-config \
    libasound2-dev \
    cmake \
    libc6 \
    binutils \
    dh-autoreconf

RUN cargo build --release
ENTRYPOINT ["ds_thread_player"]

